### ISSUE TITLE
How to visualize the attention heat map?

### ISSUE THREAD

**Issue by Donkdot** [Markin-Wang/MixViT#1]
Hello, I appreciate your work very much. Can you open source the attention visualization part of the code?

**Comment by Markin-Wang** [comment]
Hi, thanks for your interest, I have uploaded the relevant files to this repo. Note this I did not have time to clean the code in this moment, so you may need to make some changes or ignore some part of code in the file to run the code.

**Comment by Donkdot** [comment]
Thanks a lot!
